# Created by Nelson Durrant, Sep 2024
#
# DOCKER COMPOSE FILE (DEVELOPMENT IMAGE, AMD64)
# - Feel free to modify this locally to match your
#   personal computer

services:
  cougars:
    image: frostlab/cougars:latest
    build: .
    platform: linux/amd64
    container_name: cougars
    user: frostlab
    network_mode: host
    environment:
      DISPLAY: $DISPLAY # Required for GUI applications
      MPLBACKEND: Qt5Agg # Required for GUI applications
    privileged: true
    volumes:
      - ../bag:/home/frostlab/bag:rw
      - ../config:/home/frostlab/config:rw
      - ../cougars-ros2:/home/frostlab/ros2_ws
      - ../cougars-teensy:/home/frostlab/teensy_ws
      - ../cougars-gpio:/home/frostlab/gpio
      - ../cougars-docs:/home/frostlab/docs
      - /etc/localtime:/etc/localtime:ro # Syncs the container's time with the host
      - /tmp/.X11-unix:/tmp/.X11-unix # Required for GUI applications
      - /dev/shm:/dev/shm
    command: /bin/bash
    stdin_open: true  # Equivalent to -it in docker run
    tty: true  # Equivalent to -it in docker run
    restart: always  # Optional: Keeps the container running after exit unless you want it to be removed like with --rm