services:
  
  holoros-sim:
    image: frostlab/cougars:sim-holoros-cuda12.4
    build: ../cougars-base-station/sim/docker/runtime
    container_name: cougars-sim-holoros
    user: ue4
    runtime: nvidia
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      # - ../../sim-packages:/home/ue4/ros2_ws/src
      # - ~/.local/share/holoocean:/home/ue4/.local/share/holoocean
      - /dev:/dev
      - ../ros2_ws:/home/ue4/coug_ros2
      - ../cougars-base-station/sim/holo-translator:/home/ue4/sim_ws/src/holo-translator
      - ../cougars-base-station/sim/config:/home/ue4/sim_config
      - ../config:/home/ue4/config
      - ../cougars-base-station/sim/docker/runtime/entrypoint.sh:/home/ue4/entrypoint.sh
      - ../scripts:/home/ue4/scripts
    entrypoint: ["/bin/bash", "/home/ue4/entrypoint.sh"]
    restart: always  # Optional: Keeps the container running after exit unless you want it to be removed like with --rm


  cougars:
    image: frostlab/cougars:vehicle
    build: ./vehicle
    container_name: cougars
    user: frostlab
    network_mode: host
    privileged: true
    volumes:
      - ../bag:/home/frostlab/bag:rw
      - ../config:/home/frostlab/config:rw
      - ../ros2_ws:/home/frostlab/ros2_ws
      - ../cougars-teensy:/home/frostlab/teensy_ws
      - ../cougars-gpio:/home/frostlab/gpio
      - ../scripts:/home/frostlab/scripts
      # - ../moos-ivp-extend:/home/frostlab/moos-ivp-extend
      - ./vehicle/entrypoint.sh:/home/frostlab/entrypoint.sh
      - /etc/localtime:/etc/localtime:ro # Syncs the container's time with the host
      - /dev:/dev:rw
    entrypoint: /home/frostlab/entrypoint.sh
    restart: always  # Optional: Keeps the container running after exit unless you want it to be removed like with --rm

  cougars-base:
    image: frostlab/cougars:base_station
    build: ./base_station
    container_name: cougars_base
    user: frostlab
    network_mode: host
    privileged: true
    environment:
      DISPLAY: $DISPLAY # Required for GUI applications
      MPLBACKEND: Qt5Agg # Required for GUI applications
    volumes:
      - ../bag:/home/frostlab/bag:rw
      - ../config:/home/frostlab/config:rw
      - ../ros2_ws:/home/frostlab/ros2_ws
      - ../cougars-teensy:/home/frostlab/teensy_ws
      - ../cougars-gpio:/home/frostlab/gpio
      - ../scripts:/home/frostlab/scripts
      # - ../moos-ivp-extend:/home/frostlab/moos-ivp-extend
      - ../cougars-base-station:/home/frostlab/base_station
      - ../.ssh_keys:/home/frostlab/.ssh     # Syncs ssh keys for the vehicles to save and speed up the process
      - ./base_station/entrypoint.sh:/home/frostlab/entrypoint.sh
      - /etc/localtime:/etc/localtime:ro # Syncs the container's time with the host
      - /dev:/dev:rw
      - /tmp/.X11-unix:/tmp/.X11-unix # Required for GUI applications
    entrypoint: /home/frostlab/entrypoint.sh
    restart: always  # Optional: Keeps the container running after exit unless you want it to be removed like with --rm
