#!/bin/bash

##########################################################
# DEFINES THE CONTROL TEENSY ID
# - When setting up a new vehicle, do not directly edit
#   the file in ~/CougarsSetup/config; rather edit the
#   copied file generated by 'setup.sh' in ~/config (to 
#   add CONTROL_ID, etc.)
##########################################################

# To find the CONTROL_ID, plug in the control Teensy and unplug the sensors Teensy
# then run "tycmd list" and copy the listed numeric ID (ex. "15569680")
CONTROL_ID="ADD HERE"
