#!/bin/bash
# Created by Nelson Durrant, Sep 2024

##########################################################
# DEFINES THE RPI NETWORK IDS FOR BASH SCRIPT USAGE
# - When setting up a new vehicle, do not directly edit
#   the file in '~/CougarsSetup/config'; rather edit the
#   copied file generated by 'setup.sh' in '~/config'
##########################################################

# To find the STATIC_IP, run "ifconfig eth0 | grep 'inet ' | awk '{print $2}'"
# from OUTSIDE THE DOCKER CONTAINER and copy that number (ex. "192.168.194.59")
STATIC_IP="ADD HERE"
