#!/bin/bash

##########################################################
# UPLOADS TO THE CONTROL TEENSY
# - When setting up a new vehicle, do not directly edit
#   the file in ~/CougarsSetup/config; rather edit the
#   copied file generated by 'setup.sh' in ~/config (to 
#   add CONTROL_ID, etc.)
##########################################################

# To find the CONTROL_ID, plug in the control Teensy and unplug the sensors Teensy
# then run "tycmd list" and copy the listed numeric ID (ex. "15569680")
CONTROL_ID="ADD HERE"

# Prompt the user for input
echo "1) CoUGARs Control (control)"
echo "2) HoloOcean Demo (holocean_demo)"
echo "3) Custom Hex (firmware_options)"
read -p "Select an upload source (1, 2, or 3): " choice

# Handle the user's input
case $choice in
    1)
        # Option 1 (control)
        cd ~/teensy_ws/control/.pio/build/teensy41
        tycmd upload --board $CONTROL_ID firmware.hex
        ;;
    2)
        # Option 2 (holoocean_demo)
        cd ~/teensy_ws/holoocean_demo/.pio/build/teensy41
        tycmd upload --board $CONTROL_ID firmware.hex
        ;;
    3)
        # Option 3 (firmware_options)
        read -p "Enter the name of the custom hex file in firmware_options (ex. 'control.hex'):" hex_file
        cd ~/config/firmware_options
        tycmd upload --board $CONTROL_ID $hex_file
        ;;
    *)
        echo "ERROR: Invalid choice. Please select one of the listed options."
        ;;
esac
