#!/bin/bash

##########################################################
# UPLOADS TO THE SENSORS TEENSY
# - When setting up a new vehicle, do not directly edit
#   the file in ~/CougarsSetup/config; rather edit the
#   copied file generated by "setup.sh" in ~/config (to 
#   add SENSORS_ID, etc.)
##########################################################

# To find the SENSORS_ID, plug in the control Teensy and unplug the sensors Teensy
# then run "tycmd list" and copy the listed numeric ID (ex. "15569680")
SENSORS_ID="ADD HERE"

# Prompt the user for input
echo "1) CoUGARs Sensors (sensors)"
echo "2) Custom Hex (firmware_options)"
read -p "Select an upload source (1 or 2): " choice

# Handle the user's input
case $choice in
    1)
        # Option 1 (sensors)
        cd ~/teensy_ws/sensors/.pio/build/teensy41
        tycmd upload --board $SENSORS_ID firmware.hex
        ;;
    2)
        # Option 2 (firmware_options)
        read -p "Enter the name of the custom hex file in firmware_options (ex. 'sensors.hex'):" hex_file
        cd ~/config/firmware_options
        tycmd upload --board $SENSORS_ID $hex_file
        ;;
    *)
        echo "ERROR: Invalid choice. Please select one of the listed options."
        ;;
esac
