# Created by Braden Meyers, Jun 2025

services:
  cougars:
    image: frostlab/cougars:base_station
    build: .
    container_name: cougars_base
    user: frostlab
    network_mode: host
    privileged: true
    volumes:
      - ../../bag:/home/frostlab/bag:rw
      - ../../config:/home/frostlab/config:rw
      - ../../cougars-ros2:/home/frostlab/ros2_ws
      - ../../cougars-teensy:/home/frostlab/teensy_ws
      # - ../../cougars-gpio:/home/frostlab/gpio
      # - ../../moos-ivp-extend:/home/frostlab/moos-ivp-extend
      - ../../cougars-base-station:/home/frostlab/base_station
      - ../../.ssh_keys:/home/frostlab/.ssh     # Syncs ssh keys for the vehicles to save and speed up the process
      - ./entrypoint.sh:/home/frostlab/entrypoint.sh
      - /etc/localtime:/etc/localtime:ro # Syncs the container's time with the host
      - /dev:/dev:rw
      - /tmp/.X11-unix:/tmp/.X11-unix # Required for GUI applications
    entrypoint: /home/frostlab/entrypoint.sh
    restart: always  # Optional: Keeps the container running after exit unless you want it to be removed like with --rm
