#!/bin/bash
# Created by Nelson Durrant, Sep 2024
#
# Defines RPi bash constants for use in Docker bash scripts
# - When setting up a new vehicle, do not directly edit
#   the file in 'templates'; rather the copied file 
#   generated by 'setup.sh' in 'config'
# - If you edit this file, you'll need to make sure the 
#   copied file in 'config' is updated as well

# Match with the username defined in the Dockerfile
export LABNAME="frostlab"

# Match with the namespace string in 'teensy_ws/cougars/include/namespace.h'
# as well as the namespace string in 'vehicle_config.yaml'
export NAMESPACE="coug1"

# To find the STATIC_IP, run "ifconfig eth0 | grep 'inet ' | awk '{print $2}'"
# from OUTSIDE THE DOCKER CONTAINER and copy that number (ex. "192.168.194.59")
export STATIC_IP="ADD HERE"
