#!/bin/bash
# Defines RPi environment variables for use in Docker bash scripts
# - When setting up a new vehicle, do not directly edit the file in 'templates'; rather the copied file generated by 'setup.sh' in 'config'
# - If you edit this file, you'll need to make sure the copied file in 'config' is updated as well

export NAMESPACE=coug0 # ex. coug0
export VEHICLE_PARAMS_FILE=/home/frostlab/config/deploy_tmp/vehicle_params.yaml # ex. /home/frostlab/config/vehicle_params.yaml
export VEHICLE_ID=0 # ex. 0
export GPIO_CHIP=/dev/gpiochip0 # ex. /dev/gpiochip0

# Run "ifconfig eth0 | grep 'inet ' | awk '{print $2}'" from OUTSIDE THE DOCKER CONTAINER and copy that number (ex. "192.168.194.59") here
export STATIC_IP=0
export UCONTROLLER='STM' # options: STM, TEENSY
export UCONTROLLER_SERIAL='/dev/serial0' # path to serial port, defaults: /dev/serial0 for STM, /dev/frost/teensy for teensy
export DVL_IP_ADDRESS=192.168.194.95

export POWER_PIN = 27 # 27
export PROGRAM_PIN = 24 # 24

export STM_RST_GPIO=2 #mainboard default: 2
export STM_BOOT0_GPIO=3 #mainboard default: 3