#!/bin/bash
# Created by Nelson Durrant, Sep 2024
#
# Defines RPi environment variables for use in Docker bash scripts
# - When setting up a new vehicle, do not directly edit
#   the file in 'templates'; rather the copied file 
#   generated by 'setup.sh' in 'config'
# - If you edit this file, you'll need to make sure the 
#   copied file in 'config' is updated as well

# IMPORTANT!: Match with the lab name defined in the Dockerfile
export LABNAME=frostlab

# IMPORTANT!: Match with the namespace defined in 'teensy_ws/cougars/include/namespace.h'
# You need to update that namespace in the Teensy code as well
export NAMESPACE=coug1
export CONFIG_FILE=/home/$LABNAME/config/vehicle_config.yaml

# To find the STATIC_IP, run "ifconfig eth0 | grep 'inet ' | awk '{print $2}'"
# from OUTSIDE THE DOCKER CONTAINER and copy that number (ex. "192.168.194.59")
export STATIC_IP=0