'''
:author: Nelson Durrant
:date: September 2024

GPIO Pin Definitions
- When setting up a new vehicle, do not directly edit the file in 'templates'; rather the copied file generated by 'setup.sh' in 'config'
- If you edit this file, you'll need to make sure the copied file in 'config' is updated as well
'''

POWER_PIN = 27 # 27
PROGRAM_PIN = 24 # 24

STROBE_PIN = 15 # 15
STROBE_RATE = 1 # seconds

GPIO_CHIP = '/dev/gpiochip4' # ex. '/dev/gpiochip4'
