/**
 * Simple namespace declaration for micro-ROS. This is used to avoid naming
 * conflicts with the other vehicles while still keeping them all under the 
 * same ROS_DOMAIN_ID.
 * 
 * - When setting up a new vehicle, do not directly edit the file in 
 *   'templates'; rather the copied file generated by 'setup.sh' in 'config'
 * - If you edit this file, you'll need to make sure the copied file in 'config' 
 *   is updated as well
 */

#define NAMESPACE "coug0"
