name: Docker Images CI

on:
  push:
    branches: [ "main" ]
    paths: 
      - "docker/**"
  pull_request:
    branches: [ "main" ]
    paths: 
      - "docker/**"

  workflow_dispatch:

jobs:

  docker_vehicle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      if: github.event_name == 'push'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and (conditionally) push vehicle image
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:docker/vehicle"
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name == 'push' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/cougars:vehicle

  docker_base_station:
    needs: docker_vehicle
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      if: github.event_name == 'push'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and (conditionally) push base station image
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:docker/base_station"
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name == 'push' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/cougars:base_station
