name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths: 
      - "docker/Dockerfile" 
  pull_request:
    branches: [ "main" ]
    paths:
      - "docker/Dockerfile"

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to DockerHub
      uses: docker/build-push-action@v6
      with:
       context: "{{defaultContext}}:docker"
       platforms: linux/amd64,linux/arm64
       push: true
       tags: ${{ secrets.DOCKERHUB_USERNAME }}/cougars:latest
